apiVersion: v1
kind: Endpoints
metadata:
  name: ceph-metrics-svc
subsets:
  - addresses:
      - ip: 113.142.1.188  # 可以有多个
    ports:
      - name: metrics
        port: 9128
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-metrics-svc
  labels:
    service: ceph-metrics-svc
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9128
      protocol: TCP
      targetPort: 9128
