apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-prometheus-ankr-prometheus-db-prometheus-prometheus-ankr-prometheus-0
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi