apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: qgg-nfs-storage #这里的名称要和provisioner配置文件中的环境变量PROVISIONER_NAME保持一致
parameters:
  archiveOnDelete: "false"  # false代表删除pvc的时候, 清空nfs中的存储。 否则实际上nfs存储不会真正的删除, 会有archived-前缀代表删除了, 默认是true
reclaimPolicy: Delete   #只有NFS 和hostPth支持两种回收策略