# 注意把alertmanager的副本数改成1, 重新创建这个secret的时候 xx-gen也会被创建
# 先删除原先的secret然后再create创建，容器中的文件就会被更新了
apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
      "smtp_smarthost": 'smtp.qq.com:465'
      "smtp_from": '97xxxx17@qq.com'
      "smtp_auth_username": '9xxxxxx7@qq.com'
      "smtp_auth_password": 'ewlxxxxxxxmbbjd'
      "smtp_require_tls": false
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
    - "name": "Watchdog"
    - "name": "Critical"
    - "name": "Warning"
      "email_configs":
      - "to": '189xxxxxx0@163.com'
        "send_resolved": true
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "12h"
      "routes":
      - "match":
          "alertname": "Watchdog"
        "receiver": "Watchdog"
      - "match":
          "severity": "critical"
        "receiver": "Critical"
      - "match":
          "severity": "warning"
        "receiver": "Warning"
type: Opaque
