apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prodvs
  namespace: myistio
spec:
  hosts:
    - prodsvc
  http:
  - match:
    - uri:
       prefix: "/p"
    rewrite:
       uri: "/prods"
    route:
     - destination:
        host: prodsvc
        subset: v1svc   # 对应 DestinationRule
        port:
          number: 80
  - match:
    - uri:
       prefix: "/r"
    rewrite:
       uri: "/reviews"
    route:
      - destination:
          host: reviewsvc
          port:
            number: 80