apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prodvs
  namespace: myistio
spec:
  hosts:
    - pp.fyxemmmm.com
    - prodsvc
    - reviewsvc  # prodsvc内部程序会调用reviewsvc 所以reviewsvc 也得加上
  gateways:
    - pp-gateway
    - mesh
  http:
  - match:
    - uri:
       prefix: "/p"
    rewrite:
       uri: "/prods"
    fault:
      delay:
        fixedDelay: 3s  # 延迟3秒
        percentage:
          value: 100
    route:
     - destination:
        host: prodsvc
        subset: v1svc
        port:
          number: 80
  - match:
      - uri:
          prefix: "/"
#    - uri:
#       prefix: "/r"
#    rewrite:
#       uri: "/reviews"
    fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
    route:
      - destination:
          host: reviewsvc
          port:
            number: 80