apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsq
  name: nsqd
  namespace: apiservice
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 4150
      protocol: TCP
      targetPort: 4150
    - name: http
      port: 4151
      protocol: TCP
      targetPort: 4151
  selector:
    app: nsq
    component: nsqd
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsq
  name: nsqlookupd
  namespace: apiservice
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 4160
      protocol: TCP
      targetPort: 4160
    - name: http
      port: 4161
      protocol: TCP
      targetPort: 4161
  selector:
    app: nsq
    component: nsqlookupd
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nsq
  name: nsqadmin
  namespace: apiservice
spec:
  ports:
    - name: tcp
      port: 4170
      protocol: TCP
      targetPort: 4170
    - name: http
      port: 4171
      protocol: TCP
      targetPort: 4171
  selector:
    app: nsq
    component: nsqadmin
  type: ClusterIP
