version: 2
jobs:
  build:
    docker:
      - image: img:v1.0.0
    steps:
      - checkout
      - setup_remote_docker # volume  docker.sock mounts to the container
      - run:
          name: "decrypt k8s config"
          command: data=$(cat /root/.kube/oentext ); crypt aes -k=$kubekey -e=false -d=$data > /root/.kube/config
      - run:
          name: "Login Docker Repositories"
          command: docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
      - run:
          name: "Build & Push Docker Image"
          command: |
            set -x

            BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
            SHA1_SHORT=$(git rev-parse --short HEAD)
            DATE=`date +%Y%m%d%H%M%S`
            case "$BRANCH_NAME" in
              "main")
                K8S_CLUSTER="api"
                REPLICAS=2
                LEVEL="info"
                ;;
              "develop")
                K8S_CLUSTER="stage.api"
                REPLICAS=1
                LEVEL="info"
                ;;
              *)
                K8S_CLUSTER="stage.api"
                REPLICAS=1
                LEVEL="debug"
            esac

            # push image to specified ecr repo

            docker build --build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t aci-court .
            docker tag aci-court ankrnetwork/aci-court:$SHA1_SHORT$DATE
            docker push ankrnetwork/aci-court:$SHA1_SHORT$DATE

            # deploy
            kubectl config use-context $K8S_CLUSTER.k8s.ankr.network

            sed -i "s/{{TAG}}/$SHA1_SHORT$DATE/g" deployments/deployment
            sed -i "s/{{LEVEL}}/$LEVEL/g" deployments/deployment
            sed -i "s/{{REPLICAS}}/$REPLICAS/g" deployments/deployment

            kubectl apply -f deployments/deployment

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: cicd

