apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-svc-2
  namespace: redis-cluster
spec:
  type: NodePort
  ports:
    - name: redis-port
      port: 6379
    - name: meeting-port
      port: 16379
  selector:
    app: redis-2
    appCluster: redis-cluster