# 先在monitor-sa名称空间下创建一个monitor的sa, 再执行以下文件
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myadmin
rules:
  - apiGroups:
      - "*"
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myadmin-cls-binding  # 这个其实不是很重要
subjects:
  - kind: ServiceAccount
    name: monitor
    namespace: monitor-sa
roleRef:
  kind: ClusterRole
  name: myadmin   # 或者直接绑定k8s默认的cluster-admin 有默认最高权限
  apiGroup: rbac.authorization.k8s.io
