apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: apiservice
spec:
  ports:
    - name: etcd-svc-port
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: etcd
  type: ClusterIP
