apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: etcd
  name: etcd1-pv-claim
  namespace: apiservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
